import { useRef, useState, useEffect } from 'react';
import { useApp } from '../context/hooks';
import { useAuth } from '../context/AuthContext';
import { useProgress } from '../hooks/useProgress';
import type { ScheduledModule } from '../types';
import './ExportButton.css';

export function ExportButton() {
  const { state } = useApp();
  const { user } = useAuth();
  const { roadmap } = state;
  const { lastSync } = useProgress(user?.id || null);
  const [isOpen, setIsOpen] = useState(false);
  const [exporting, setExporting] = useState<'idle' | 'pdf' | 'ical' | 'json' | 'sync'>('idle');
  const [error, setError] = useState<string | null>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  // Close dropdown when clicking outside - moved before early return
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  if (!roadmap) return null;
  
  const generatePDF = async () => {
    setExporting('pdf');
    setError(null);
    try {
      const printWindow = window.open('', '_blank');
      if (!printWindow) throw new Error('Popup blocked - please allow popups');
      
      const modules = roadmap.modules;
      const pathName = roadmap.pathName;
      const totalHours = roadmap.totalHours;
      const deadline = roadmap.deadline;
      const generatedAt = new Date(roadmap.generatedAt).toLocaleDateString();
      
      const html = `
<!DOCTYPE html>
<html>
<head>
  <title>${pathName} Roadmap</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
    h2 { color: #666; margin-top: 30px; }
    .meta { display: flex; gap: 30px; margin: 20px 0; flex-wrap: wrap; }
    .meta-item { background: #f3f4f6; padding: 10px 20px; border-radius: 8px; }
    .meta-label { font-size: 12px; color: #666; text-transform: uppercase; }
    .meta-value { font-weight: bold; font-size: 18px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #e5e7eb; }
    th { background: #f9fafb; font-weight: 600; }
    .status-badge { padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 500; }
    .status-pending { background: #f3f4f6; color: #374151; }
    .status-in-progress { background: #dbeafe; color: #1e40af; }
    .status-done { background: #d1fae5; color: #065f46; }
    .checklist { margin-top: 40px; }
    .checklist-item { margin: 8px 0; }
    .footer { margin-top: 50px; text-align: center; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <h1>${pathName} Roadmap</h1>
  <div class="meta">
    <div class="meta-item">
      <div class="meta-label">Generated</div>
      <div class="meta-value">${generatedAt}</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Deadline</div>
      <div class="meta-value">${deadline}</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Total Hours</div>
      <div class="meta-value">${totalHours}h</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Weeks</div>
      <div class="meta-value">${roadmap.weeklySchedule.length}</div>
    </div>
  </div>
  
  <h2>Module Timeline</h2>
  <table>
    <thead>
      <tr>
        <th>Module</th>
        <th>Weeks</th>
        <th>Hours</th>
        <th>Dependencies</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      ${modules.map(m => `
        <tr>
          <td>${m.name}</td>
          <td>W${m.startWeek}–W${m.endWeek}</td>
          <td>${m.assignedHours}h</td>
          <td>${m.dependencies.join(', ') || '—'}</td>
          <td><span class="status-badge status-${m.status}">${m.status.replace('-', ' ')}</span></td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  
  <h2>Weekly Schedule</h2>
  <table>
    <thead>
      <tr>
        <th>Week</th>
        <th>Modules</th>
        <th>Hours</th>
        <th>Milestones</th>
      </tr>
    </thead>
    <tbody>
      ${roadmap.weeklySchedule.map(w => `
        <tr>
          <td>Week ${w.week}</td>
          <td>${w.moduleIds.map(id => modules.find(m => m.id === id)?.name).filter(Boolean).join(', ') || '—'}</td>
          <td>${w.hoursAllocated}h</td>
          <td>${w.milestones.join(', ') || '—'}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  
  <div class="checklist">
    <h2>Completion Checklist</h2>
    ${modules.map(m => `
      <div class="checklist-item">
        <input type="checkbox" id="task-${m.id}"> 
        <label for="task-${m.id}">${m.name}</label>
      </div>
    `).join('')}
  </div>
  
  <div class="footer">
    Generated by CS Internship Roadmap App • ${new Date().toLocaleDateString()}
  </div>
</body>
</html>
      `;
      
      printWindow.document.write(html);
      printWindow.document.close();
      
      printWindow.onload = () => {
        setTimeout(() => {
          printWindow.print();
          setTimeout(() => printWindow.close(), 1000);
        }, 500);
      };
      
      setExporting('idle');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate PDF');
      setExporting('idle');
    }
  };
  
  const generateICal = () => {
    setExporting('ical');
    setError(null);
    try {
      const generatedDate = new Date(roadmap.generatedAt);
      const startDate = new Date(generatedDate);
      startDate.setHours(9, 0, 0, 0);
      
      const icsLines: string[] = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//CS Internship Roadmap App//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        'X-WR-CALNAME:CS Internship Roadmap',
      ];
      
      roadmap.modules.forEach((module: ScheduledModule) => {
        const moduleStart = new Date(startDate);
        moduleStart.setDate(startDate.getDate() + (module.startWeek - 1) * 7);
        
        const moduleEnd = new Date(startDate);
        moduleEnd.setDate(startDate.getDate() + module.endWeek * 7);
        
        const formatDate = (date: Date) => 
          date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
        
        icsLines.push(
          'BEGIN:VTODO',
          `UID:${module.id}-${Date.now()}@roadmap.app`,
          `DTSTAMP:${formatDate(new Date())}`,
          `DTSTART:${formatDate(moduleStart)}`,
          `DUE:${formatDate(moduleEnd)}`,
          `SUMMARY:[${module.assignedHours}h] ${module.name}`,
          `DESCRIPTION:${module.description}\\n\\nDependencies: ${module.dependencies.join(', ') || 'None'}\\n\\nKey Points:\\n${module.key_points.map(kp => `- ${kp}`).join('\\n')}`,
          `CATEGORIES:STUDY`,
          `STATUS:${module.status === 'done' ? 'COMPLETED' : module.status === 'in-progress' ? 'IN-PROCESS' : 'NEEDS-ACTION'}`,
          `PRIORITY:${module.dependencies.length > 0 ? 1 : 5}`,
          'END:VTODO'
        );
      });
      
      const deadlineDate = new Date(roadmap.deadline);
      deadlineDate.setHours(23, 59, 0, 0);
      const formatDate = (date: Date) => date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
      
      icsLines.push(
        'BEGIN:VEVENT',
        `UID:deadline-${Date.now()}@roadmap.app`,
        `DTSTAMP:${formatDate(new Date())}`,
        `DTSTART:${formatDate(deadlineDate)}`,
        `SUMMARY:🎯 Internship Application Deadline`,
        `DESCRIPTION:Your target date to start applying for internships.\\nRoadmap: ${roadmap.pathName}\\nTotal Hours: ${roadmap.totalHours}h`,
        'END:VEVENT'
      );
      
      icsLines.push('END:VCALENDAR');
      
      const icsContent = icsLines.join('\r\n');
      const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      
      const link = document.createElement('a');
      link.href = url;
      link.download = `${roadmap.pathName.replace(/\s+/g, '-').toLowerCase()}-roadmap.ics`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      setExporting('idle');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate iCal');
      setExporting('idle');
    }
  };
  
  const generateJSON = () => {
    setExporting('json');
    setError(null);
    try {
      const json = JSON.stringify(roadmap, null, 2);
      const blob = new Blob([json], { type: 'application/json' });
      const url = URL.createObjectURL(blob);

      const link = document.createElement('a');
      link.href = url;
      link.download = `roadmap-${Date.now()}.json`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      setExporting('idle');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate JSON');
      setExporting('idle');
    }
  };

  const handleSync = () => {
    setExporting('sync');
    setError(null);
    try {
      // Trigger sync by dispatching a custom event that the ProgressProvider will listen to
      window.dispatchEvent(new CustomEvent('sync-progress'));
      setTimeout(() => {
        setExporting('idle');
      }, 1000);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to sync progress');
      setExporting('idle');
    }
  };
  
  return (
    <div className="export-button-wrapper" ref={dropdownRef}>
      <div className="export-button-trigger">
        <button
          onClick={() => setIsOpen(!isOpen)}
          disabled={exporting !== 'idle'}
          className="btn btn-secondary"
          aria-expanded={isOpen}
          aria-haspopup="true"
        >
          <svg className="btn-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          <span>Export</span>
          <svg className="btn-icon btn-chevron" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </button>
        
        {isOpen && (
          <div className="export-dropdown">
            {user && (
              <>
                <button
                  onClick={handleSync}
                  disabled={exporting !== 'idle'}
                  className={`dropdown-item sync-item ${exporting === 'sync' ? 'loading' : ''}`}
                >
                  <svg className="dropdown-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                  </svg>
                  <div className="sync-info">
                    <span>{exporting === 'sync' ? 'Syncing...' : 'Sync Progress'}</span>
                    {lastSync && (
                      <small>Last synced: {lastSync.toLocaleTimeString()}</small>
                    )}
                  </div>
                </button>
                <div className="dropdown-divider"></div>
              </>
            )}
            <button
              onClick={generatePDF}
              disabled={exporting !== 'idle'}
              className={`dropdown-item ${exporting === 'pdf' ? 'loading' : ''}`}
            >
              <svg className="dropdown-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
              </svg>
              <span>{exporting === 'pdf' ? 'Generating...' : 'Download PDF'}</span>
            </button>
            <button
              onClick={generateICal}
              disabled={exporting !== 'idle'}
              className={`dropdown-item ${exporting === 'ical' ? 'loading' : ''}`}
            >
              <svg className="dropdown-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
              <span>{exporting === 'ical' ? 'Generating...' : 'Download iCal (.ics)'}</span>
            </button>
            <button
              onClick={generateJSON}
              disabled={exporting !== 'idle'}
              className={`dropdown-item ${exporting === 'json' ? 'loading' : ''}`}
            >
              <svg className="dropdown-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
              </svg>
              <span>{exporting === 'json' ? 'Generating...' : 'Download JSON'}</span>
            </button>

            {error && (
              <div className="dropdown-error">
                Error: {error}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}